service: Auction-Service
frameworkVersion: '2'

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    AUCTIONS_TABLE: ${self:service}-${self:opt, self:provider.stage}-auctions
  iamRoleStatements:
    - 
      Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arnarn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.AUCTIONS_TABLE}
  
resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.AUCTIONS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      migrate: true
      inMemory: true
      onStart: true